### PR TITLE
Attach running process

### LINKED ISSUE #6: Implement process attach support

### PR DESCRIPTION
**Pull request by akihikodaki**
Closes #6.

### CODE REVIEW

**Comment by akihikodaki** [comment]
I was not aware of `connect` command.

Well, maybe those who have used gdb before will look for `attach` command and may have misconception that the feature is not implemented. That is exactly my case. I think this command should be implemented as an alias or removed. Which do you prefer, or do you have another idea?

**Comment by thaystg** [comment]
I think that attach should be implemented to be used with PID as gdb.
But to avoid this misconception, we can put a message like:
"Attempts to attach to the given process ID.\n" +
                       "\n" +
                       "Currently unimplemented.\nUse connect command."
What do you think?

**Comment by alexrp** [comment]
> I think that attach should be implemented to be used with PID as gdb.

This was the original intention, but I never got around to implementing it this way because (at least at the time) that seemed fairly non-trivial and would probably have involved using Mono's general-purpose assembly attach mechanism: https://github.com/mono/mono/blob/master/mono/metadata/attach.c

It's quite possible the VSfM team figured out a better solution in the meantime though. I'm not up to date on the issue.

I have no objection to updating `attach`'s help text to point to the `connect` command until it's actually implemented.

**Comment by akihikodaki** [comment]
Anyway, this change for `attach` command is no longer relevant. I'll close this pull request.

**Pull request closed without merging**
